name: my_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (required for all Firebase services)
  firebase_core: ^3.6.0

  # Authentication (login/signup)
  firebase_auth: ^5.3.0

  # Cloud Firestore (database)
  cloud_firestore: ^5.4.4

  # Firebase Storage (upload images/files)
  firebase_storage: ^12.3.4

  # Firebase Messaging (push notifications)
  firebase_messaging: ^15.1.3

  # UI Icons
  cupertino_icons: ^1.0.8

  # OpenStreetMap plugin for Flutter
  flutter_osm_plugin: ^0.70.4

  # ðŸ”¹ Geolocator for location services (stable version)
  geolocator: ^9.0.2



  # ðŸ”¹ Permission handler (stable)
  permission_handler: ^11.4.0

    # ðŸ”¹ Charts for Reports tab
  fl_chart: 


  # ðŸ”¹ URL launcher if needed
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  vector_math: ^2.2.0

 

flutter:
  uses-material-design: true
